language: python
sudo: false

env:
  matrix:
    - PYTHON=2.7 NUMPY=1.10.4 PANDAS=0.18.0 COVERAGE='true' XTRATESTARGS=
    - PYTHON=2.7 NUMPY=1.11.0 PANDAS=0.18.1 COVERAGE='false' PYTHONOPTIMIZE=2 XTRATESTARGS=--ignore=dask/diagnostics
    - PYTHON=3.3 NUMPY=1.9.2 PANDAS=0.18.1 COVERAGE='false' XTRATESTARGS=
    - PYTHON=3.4 NUMPY=1.10.4 PANDAS=0.18.0 COVERAGE='false' PYTHONOPTIMIZE=2 XTRATESTARGS=--ignore=dask/diagnostics
    - PYTHON=3.5 NUMPY=1.11.0 PANDAS=0.18.1 COVERAGE='false' XTRATESTARGS=

addons:
    apt:
        packages:
        - graphviz
        - liblzma-dev

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-environment python=$PYTHON
  - source activate test-environment
  - conda install numpy=$NUMPY scipy pytables h5py bcolz pytest coverage toolz scikit-learn cytoolz chest blosc cython psutil ipython
  - if [[ $PYTHON != '3.3' ]]; then conda install pandas=$PANDAS distributed cloudpickle bokeh; fi
  - if [[ $PYTHON == '3.3' ]]; then pip install cloudpickle pandas==$PANDAS; fi
  - if [[ $PYTHON == '2.7' ]]; then pip install backports.lzma mock; fi
  - pip install git+https://github.com/mrocklin/partd --upgrade
  - pip install git+https://github.com/mrocklin/cachey --upgrade
  - pip install blosc --upgrade
  - pip install graphviz moto flake8
  - if [[ $PYTHON < '3' ]]; then pip install git+https://github.com/Blosc/castra; fi

  # Install dask
  - pip install --no-deps -e .[complete]

script:
    - if [[ $COVERAGE == 'true' ]]; then coverage run $(which py.test) dask --runslow --doctest-modules --verbose $XTRATESTARGS; else py.test dask --runslow --verbose $XTRATESTARGS; fi

after_success:
    - if [[ $coverage == 'true' ]]; then coverage report --show-missing; pip install coveralls ; coveralls ; fi

notifications:
  email: false
